### ISSUE TITLE
include references for where constants are obtained from in autogen_parameters.csv file

### ISSUE THREAD

**Issue by FinbarArgus** [physiomelinks/circulatory_autogen#1]
Atm it is not specified whether each parameter is identified from data, obtained from literature, or measurement. I plan on including another column in the autogen_parameters.csv file that references where the value comes from. The short reference messages in the file, such as "Blanco2016" will, be described in another file called data_references.txt.

By including this I can have a references "Identified_from_data" and "to_be_identified_from_data" So we can put checks in the autogeneration code that warns if the parameters used have not yet been identified from physiological data.

**Comment by ssafaei** [comment]
I cited all the references in the parameters_autogen.csv file.

**Comment by FinbarArgus** [comment]
Hi Soroush, 

Thank you! Could you please specify what fork and branch you have done this in?
